export const APPLICATION_OPTIONS = 'APPLICATION_OPTIONS';
export const ASYNC_OPTIONS_TOKEN = 'ASYNC_OPTIONS_TOKEN';
export const LOADER_SOURCE_TOKEN = 'LOADER_SOURCE_TOKEN';
export const SERVICE_INIT_TOKEN = 'SERVICE_INIT_TOKEN';
export const ENVIRONMENT_OPTIONS_TOKEN = 'ENVIRONMENT_OPTION_TOKEN';
